### ISSUE TITLE
False negative when using direct client without readiness await

### ISSUE THREAD

**Issue by harryfear** [Unleash/proxy-client-svelte#16]
### Describe the bug

Weird behaviour from e.g. habits library: SDK says a feature flag is ‘off’, when it's actually ‘on’ (and the AJAX API request confirms its on).

Weirdly, using a 0ms setTimeout on mount seems to solve the issue.

### Steps to reproduce the bug

```
// +page.svelte
<script>
    import {
        useUnleashContext,
        useUnleashClient,
    } from "@unleash/proxy-client-svelte";
    // useUnleashContext is necessary if the context is necessary for the flag to be fetched truthfully

    import { onMount } from "svelte"; // Only for console logging

    const client = useUnleashClient();

    let status = ""; // Optionally print the result to HTML reactively

    onMount(() => {
            // login user
            if (
                client.isEnabled("maxHabitsIncreased") // Returns a boolean 'directly' (with no subscription)
            ) {
                console.log("ON"); // Console print-out
                status = "On!"; // Update DOM for HTML print-out
            } else {
                console.log("OFF"); // Console print-out
                status = "Off"; // Update DOM for HTML print-out
            }
    });
</script>

{status}
```

### Expected behavior

Expect to see ‘on’ when the flag is indeed turned on; but instead see ‘off’ only when using the [direct client syntax](https://docs.getunleash.io/reference/sdks/svelte#use-unleash-client-directly).

Bizarrely, the issue disappears if we add a 0ms setTimeout wrapper:
```
<script>
    import {
        useUnleashContext,
        useUnleashClient,
    } from "@unleash/proxy-client-svelte";

    import { onMount } from "svelte"; // Only for console logging

    const client = useUnleashClient();

    let status = ""; // Optionally print the result to HTML reactively

    onMount(() => {
        setTimeout(() => {
            // login user
            if (
                client.isEnabled("maxHabitsIncreased") // Returns a boolean 'directly' (with no subscription)
            ) {
                console.log("ON"); // Console print-out
                status = "On!"; // Update DOM for HTML print-out
            } else {
                console.log("OFF"); // Console print-out
                status = "Off"; // Update DOM for HTML print-out
            }
        }, 0); // No real wait
    });
</script>

{status}

```

### Screenshots

![image](https://github.com/Unleash/proxy-client-svelte/assets/907604/124047dd-c469-4389-8b6e-0b9efcb7ee3c)

The server responds with the true value, but it appears the SDK is not honouring it for some reason.

### Additional context

The SDK otherwise works completely as expected; it's only in this ‘direct client’ syntax does it fail to accurately truthfully report.

### Unleash version

Svelte Client SDK issue.

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

"@unleash/proxy-client-svelte": "^0.3.0"

**Comment by harryfear** [comment]
I see that using `setTimeout(() => {` pushes the execution out of the current call stack and allows the Unleash client time to become ready.

I see also that deliberately awaiting client readiness is also another option; but shouldn't this be in the docs?
```
client.on("ready", () => {
// This works
});
```

**Comment by nunogois** [comment]
Hi @harryfear,

If I understood correctly, I believe the SDK is working as intended. This should be the same behavior you would see across all our frontend SDKs.

You can find the [Defer rendering until flags fetched](https://github.com/Unleash/proxy-client-svelte?tab=readme-ov-file#defer-rendering-until-flags-fetched) section in the README and [docs](https://docs.getunleash.io/reference/sdks/svelte#defer-rendering-until-flags-fetched).

**Comment by harryfear** [comment]
Thanks for the super-fast response!

I was just surprised to see the SDK returning a ‘false’, even when the Unleash API was saying true.

But if that's intended behaviour, then OK.

I just would have expected it to return undefined or hang, rather than respond with ‘false’. 🙏🏼
