### ISSUE TITLE
Svelte 5 compatibility

### ISSUE THREAD

**Issue by ryanbmarx** [Unleash/proxy-client-svelte#17]
### Describe the feature request

As the svelte world transitions to v5, the proxy client lists v4 as a peer dependency. Are there plans to update to v5? Or, possibly update the peer dep since v4/5 are "interchangeable" for now.

### Solution suggestions

An immediate solution would be to alter the peer dependency, so at least CI pipelines that use Unleash+Svelte could do so without force installing.

**Comment by nunogois** [comment]
Hi @ryanbmarx, thank you for raising this issue!

Could you share a bit more detail about what you have in mind for the change?

If you’re interested, feel free to open a PR with your suggestion. We’d be happy to review it!

**Comment by ryanbmarx** [comment]
Hi @nunogois Thank you so much for your attention to this. I created a PR with my proposed change. https://github.com/Unleash/proxy-client-svelte/pull/18

**Comment by nunogois** [comment]
Thank you again for raising the issue and submitting your contribution @ryanbmarx! This is now available in [v0.4.0](https://github.com/Unleash/proxy-client-svelte/releases/tag/v0.4.0) 🎉
